/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#f1ede8",
        "tertiary-fixed-dim": "#d3c4b9",
        "on-background": "#1c1c19",
        "surface-variant": "#e6e2dd",
        "surface-container-lowest": "#ffffff",
        "outline": "#83746e",
        "primary": "#5f3928",
        "text-muted": "#8C7164",
        "secondary-fixed-dim": "#e3bfad",
        "surface-bright": "#fdf9f4",
        "tertiary": "#4b4139",
        "primary-container": "#7a503d",
        "outline-variant": "#d5c3bc",
        "on-secondary-container": "#795c4e",
        "on-tertiary-fixed": "#221a13",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#1c1c19",
        "on-secondary-fixed-variant": "#5b4134",
        "on-tertiary-container": "#dfcfc4",
        "on-secondary-fixed": "#2a170c",
        "primary-fixed-dim": "#f2baa2",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f4f0eb",
        "secondary-fixed": "#ffdbca",
        "on-surface-variant": "#51443f",
        "primary-fixed": "#ffdbcc",
        "on-primary-fixed": "#311305",
        "on-primary-container": "#fec5ad",
        "surface-container-low": "#f7f3ee",
        "overlay-cream": "rgba(253, 249, 244, 0.85)",
        "surface-container-highest": "#e6e2dd",
        "surface": "#fdf9f4",
        "tertiary-container": "#63584f",
        "error": "#ba1a1a",
        "surface-dim": "#ddd9d5",
        "secondary": "#74584a",
        "surface-container-high": "#ebe8e3",
        "on-tertiary-fixed-variant": "#4f453d",
        "error-container": "#ffdad6",
        "secondary-container": "#fed8c5",
        "on-primary-fixed-variant": "#643d2b",
        "inverse-primary": "#f2baa2",
        "surface-tint": "#7f5441",
        "on-tertiary": "#ffffff",
        "surface-white": "#FFFFFF",
        "tertiary-fixed": "#f0e0d4",
        "on-secondary": "#ffffff",
        "background": "#fdf9f4",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "section-gap-md": "64px",
        "stack-md": "16px",
        "container-max": "1280px",
        "section-gap-lg": "96px",
        "stack-lg": "24px",
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-lg": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "price": ["DM Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "price": ["20px", { lineHeight: "1", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
